pandas , numpy , matplotlib , Sklearn - scikit learn , pipeine machine learning 

## Numpy

In [4]:
import numpy as np ##alias

In [6]:
np

<module 'numpy' from '/Users/rahulgarg/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>

In [7]:
a = np.array([1,2,3,4,5])

In [8]:
type(a)

numpy.ndarray

In [10]:
print(a.shape)

(5,)


In [12]:
b = np.array([[1],[2],[3],[4],[5]])
print(type(b))
print(b.shape)

<class 'numpy.ndarray'>
(5, 1)


In [13]:
c = np.array([[1,2,3], [2,3,4]])
print(c.shape)

(2, 3)


In [14]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
5*np.ones([3,4])

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.randint(7)

5

In [64]:
random = np.random.random((10,))

In [104]:

# random = np.array([0,1,2,3,4,5,6,7,8,9,10])
random = np.random.random((10,))
print(random)

[0.51665295 0.34040496 0.88410934 0.85660749 0.95539332 0.01652279
 0.28476634 0.01121545 0.98733693 0.05963238]


In [105]:
rand = random[4:-2]

print(rand)

[0.95539332 0.01652279 0.28476634 0.01121545]


In [90]:
c = np.zeros([3,4] , dtype = np.float32)

In [91]:
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [94]:

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [95]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [97]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [115]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [117]:
d = np.stack((x,y) , axis=0)
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [118]:
d.reshape((-1,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [119]:
print(x)

[[1 2]
 [3 4]]


In [129]:
x = x.reshape((-1,4))

In [130]:
x

array([[1, 2, 3, 4]])

In [131]:
# min , max , mean , median , variance , standard derivation

In [155]:
np.random.seed(6)
np.random.randint(10)

9

In [172]:
e = np.array([1,2,3,4,5,6,7,8])

In [173]:
(np.random.shuffle(e))
e

array([8, 2, 5, 4, 7, 3, 6, 1])

In [178]:
print(np.random.choice(e))

4
